leftnav:
- identifier: e266e7e3-8666-4347-a478-30bdcfa8f1d3
  name: Online Publication
  pageRef: /external-resources/online-publication_e266e7e3-8666-4347-a478-30bdcfa8f1d3
  weight: 10
- identifier: c6d67c43-7905-4bde-b02e-4acfe7773dd4
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 20
- identifier: 9183899c-2a32-4f59-bd37-283eb54b3b20
  name: Online Textbook
  pageRef: /pages/readings
  weight: 30
